version: '3.8'

services:
  # backend:
  #   build:
  #     context: ./Backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./Backend:/app
  #   depends_on:
  #     - db
  #   networks: 
  #     - app

  # frontend:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./Frontend:/usr/src/app
  #     - ./Frontend/node_modules:/usr/src/app/node_modules
  #   # depends_on:
  #   #   - backend
  #   networks:
  #     - app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql_data: